import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./componets/Sidebar";
import Navbar from "./componets/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Navbar />
        <div className="flex">
          <Sidebar />
          <div className="md:w-5/6">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
